os:
  editPreset: "nvim"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side --line-numbers --syntax-theme="gruvbox-dark"

gui:
  nerdFontsVersion: "3"
  border: single
  theme:
    activeBorderColor:
      - '#fabd2f'
      - bold
    inactiveBorderColor:
      - '#7c6f64'
    optionsTextColor:
      - '#83a598'
    selectedLineBgColor:
      - '#3c3836'
    cherryPickedCommitBgColor:
      - '#b16286'
    cherryPickedCommitFgColor:
      - '#fabd2f'
    unstagedChangesColor:
      - '#fb4934'
    defaultFgColor:
      - '#ebdbb2'
    searchingActiveBorderColor:
      - '#fe8019'

